# Generated by Django 4.2.5 on 2023-10-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HW8', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
